import { Component, Input } from '@angular/core';
import * as chroma from 'chroma-js';

@Component({
  selector: 'worldmap-chart',
  templateUrl: './worldmap-chart.component.html',
  styleUrls: [
    './worldmap-chart.component.styl'
  ]
})

export class WorldMapChart {
  @Input() data: any;

  fill = {
    "AE" : "",
    "AF" : "",
    "AL" : "",
    "AM" : "",
    "AO" : "",
    "AR" : "",
    "AT" : "",
    "AU" : "",
    "AZ" : "",
    "BA" : "",
    "BD" : "",
    "BE" : "",
    "BF" : "",
    "BG" : "",
    "BI" : "",
    "BJ" : "",
    "BN" : "",
    "BO" : "",
    "BR" : "",
    "BS" : "",
    "BT" : "",
    "BW" : "",
    "BY" : "",
    "BZ" : "",
    "CA" : "",
    "CD" : "",
    "CF" : "",
    "CG" : "",
    "CH" : "",
    "CI" : "",
    "CL" : "",
    "CM" : "",
    "CN" : "",
    "CO" : "",
    "CR" : "",
    "CU" : "",
    "CY" : "",
    "CZ" : "",
    "DE" : "",
    "DJ" : "",
    "DK" : "",
    "DO" : "",
    "DZ" : "",
    "EC" : "",
    "EE" : "",
    "EG" : "",
    "EH" : "",
    "ER" : "",
    "ES" : "",
    "ET" : "",
    "FK" : "",
    "FI" : "",
    "FJ" : "",
    "FR" : "",
    "GA" : "",
    "GB" : "",
    "GE" : "",
    "GF" : "",
    "GH" : "",
    "GL" : "",
    "GM" : "",
    "GN" : "",
    "GQ" : "",
    "GR" : "",
    "GT" : "",
    "GW" : "",
    "GY" : "",
    "HN" : "",
    "HR" : "",
    "HT" : "",
    "HU" : "",
    "ID" : "",
    "IE" : "",
    "IL" : "",
    "IN" : "",
    "IQ" : "",
    "IR" : "",
    "IS" : "",
    "IT" : "",
    "JM" : "",
    "JO" : "",
    "JP" : "",
    "KE" : "",
    "KG" : "",
    "KH" : "",
    "KP" : "",
    "KR" : "",
    "XK" : "",
    "KW" : "",
    "KZ" : "",
    "LA" : "",
    "LB" : "",
    "LK" : "",
    "LR" : "",
    "LS" : "",
    "LT" : "",
    "LU" : "",
    "LV" : "",
    "LY" : "",
    "MA" : "",
    "MD" : "",
    "ME" : "",
    "MG" : "",
    "MK" : "",
    "ML" : "",
    "MM" : "",
    "MN" : "",
    "MR" : "",
    "MW" : "",
    "MX" : "",
    "MY" : "",
    "MZ" : "",
    "NA" : "",
    "NC" : "",
    "NE" : "",
    "NG" : "",
    "NI" : "",
    "NL" : "",
    "NO" : "",
    "NP" : "",
    "NZ" : "",
    "OM" : "",
    "PA" : "",
    "PE" : "",
    "PG" : "",
    "PH" : "",
    "PL" : "",
    "PK" : "",
    "PR" : "",
    "PS" : "",
    "PT" : "",
    "PY" : "",
    "QA" : "",
    "RO" : "",
    "RS" : "",
    "RU" : "",
    "RW" : "",
    "SA" : "",
    "SB" : "",
    "SD" : "",
    "SE" : "",
    "SI" : "",
    "SJ" : "",
    "SK" : "",
    "SL" : "",
    "SN" : "",
    "SO" : "",
    "SR" : "",
    "SS" : "",
    "SV" : "",
    "SY" : "",
    "SZ" : "",
    "TD" : "",
    "TF" : "",
    "TG" : "",
    "TH" : "",
    "TJ" : "",
    "TL" : "",
    "TM" : "",
    "TN" : "",
    "TR" : "",
    "TT" : "",
    "TW" : "",
    "TZ" : "",
    "UA" : "",
    "UG" : "",
    "US" : "",
    "UY" : "",
    "UZ" : "",
    "VE" : "",
    "VN" : "",
    "VU" : "",
    "YE" : "",
    "ZA" : "",
    "ZM" : "",
    "ZW" : ""
  };

  fillChart() {
    if (!this.data.length) {
      return;
    }

    const max = Math.max.apply(Math, this.data.map(o => o.count));

    // colors from
    // https://vis4.net/labs/multihue/#colors=lightyellow,%20orange,%20deeppink,%20darkred|steps=9|bez=1|coL=1
    const scale = chroma.scale(['#ffffe0', '#ffe0a9', '#ffbe84', '#ff986d', '#f47361', '#e35056', '#cb2f44', '#ae112a', '#8b0000']).domain([0, max]);

    this.data.map(item => {
      // 'cc' = 'country code'
      const cc = item._id;

      if (cc && this.fill.hasOwnProperty(cc)) {
        this.fill[cc] = scale(item.count);
      }
    });
  }

  ngOnChanges() {
    this.fillChart();
  }
}
